### ISSUE TITLE
reflect.Value.Interface: cannot return value obtained from unexported field or method 

### ISSUE THREAD

**Issue by ginkoob** [kr/pretty#27]
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method [recovered]
	panic: reflect.Value.Interface: cannot return value obtained from unexported field or method

goroutine 20 [running]:
testing.tRunner.func1(0xc8200ba3f0)
	/usr/local/gosrc/src/testing/testing.go:450 +0x171
reflect.valueInterface(0x6d5a60, 0xc820222420, 0xe6, 0x1, 0x0, 0x0)
	/usr/local/gosrc/src/reflect/value.go:912 +0xe7
reflect.Value.Interface(0x6d5a60, 0xc820222420, 0xe6, 0x0, 0x0)
	/usr/local/gosrc/src/reflect/value.go:901 +0x48
github.com/kr/pretty.diffWriter.diff(0x7f6d2c25a078, 0xc820216440, 0xc82021a400, 0x10, 0x6d5a60, 0xc820222420, 0xe6, 0x6d5a60, 0xc8200a0bd0, 0xe6)
	/root/go/src/github.com/kr/pretty/diff.go:63 +0x49b
github.com/kr/pretty.diffWriter.diff(0x7f6d2c25a078, 0xc820216440, 0xc82021a3d0, 0xc, 0x771a20, 0xc820222420, 0xd9, 0x771a20, 0xc8200a0bd0, 0xd9)
	/root/go/src/github.com/kr/pretty/diff.go:87 +0x30cf
github.com/kr/pretty.diffWriter.diff(0x7f6d2c25a078, 0xc820216440, 0x7d5550, 0x9, 0x6c5660, 0xc8202101e0, 0xd7, 0x6c5660, 0xc82009a500, 0xd7)
	/root/go/src/github.com/kr/pretty/diff.go:97 +0x2aff
github.com/kr/pretty.diffWriter.diff(0x7f6d2c25a078, 0xc820216440, 0x0, 0x0, 0x7839c0, 0xc8202101e0, 0xd9, 0x7839c0, 0xc82009a500, 0xd9)
	/root/go/src/github.com/kr/pretty/diff.go:87 +0x30cf
github.com/kr/pretty.diffWriter.diff(0x7f6d2c25a078, 0xc820216440, 0x0, 0x0, 0x6b9240, 0xc8202101e0, 0x16, 0x6b9240, 0xc82009a500, 0x16)
	/root/go/src/github.com/kr/pretty/diff.go:83 +0x1e51
github.com/kr/pretty.Fdiff(0x7f6d2c25a078, 0xc820216440, 0x6b9240, 0xc8202101e0, 0x6b9240, 0xc82009a500)
	/root/go/src/github.com/kr/pretty/diff.go:25 +0x10e
github.com/kr/pretty.Diff(0x6b9240, 0xc8202101e0, 0x6b9240, 0xc82009a500, 0x0, 0x0, 0x0)
	/root/go/src/github.com/kr/pretty/diff.go:19 +0xa0

**Comment by dominicbarnes** [comment]
I have this issue too, and I'm not sure what to do about it.

**Comment by tve** [comment]
same here...

**Comment by kr** [comment]
This should be fixed in c49dea8a01a44a81bc4a764d6d986ebe21735bf9.
