### ISSUE TITLE
%s stopped working correctly

### ISSUE THREAD

**Issue by niemeyer** [kr/pretty#37]
This correctly prints `foo` up to add1dbc86daf0f983cd4a48ceb39deb95c729b67, and prints `&{%!s(int=1)}` after c49dea8a01a44a81bc4a764d6d986ebe21735bf9:

```
package main

import "github.com/kr/pretty"

type T struct{ I int }

func (v *T) String() string { return "foo" }

func main() { pretty.Printf("%s\n", &T{1}) }
```

**Comment by kr** [comment]
Fixed in #38.
