### ISSUE TITLE
Allow an option for 'deterministic'  iteration order for map prints

### ISSUE THREAD

**Issue by xbeta** [kr/pretty#47]
Go (since 1.1) is well-known for having randomized map iteration order. 

> When iterating over a map with a range loop, the iteration order is not specified and is not guaranteed to be the same from one iteration to the next. Since Go 1 the runtime randomizes map iteration order, as programmers relied on the stable iteration order of the previous implementation.
[https://blog.golang.org/go-maps-in-action](go-maps-in-action)

I actually use this `kr/pretty` module to do a simple string compare and found that the ordering is randomized.

`Parameters: {\"date\":\"2020-08-20\", \"digit\":\"123\"}
`
vs

`Parameters: {\"digit\":\"123\", \"date\":\"2020-08-20\"}
`

I am here requesting an option for the user to choose if they want to iterate map in an deterministic order or not. (By default, it should be not deterministic as recommended practice by Go)

**Comment by kr** [comment]
Great suggestion. IMO this package should just always sort map keys.

**Comment by rogpeppe** [comment]
FWIW you could vendor the [internal/fmtsort](https://github.com/golang/go/tree/master/src/internal/fmtsort) package or import it from github.com/rogpeppe/go-internal.

**Comment by myitcv** [comment]
Arriving here because of a bug caused by non-deterministic output 😄

**Comment by myitcv** [comment]
Raised https://github.com/kr/pretty/pull/67
