### ISSUE TITLE
type compare

### ISSUE THREAD

**Issue by egachen** [kr/pretty#49]
in function func (w diffPrinter) diff(av, bv reflect.Value) 

at := av.Type()
bt := bv.Type()
if at != bt{

can this at be compared with bt directly? I suspect it should be at.String() != bt.String()

**Comment by kr** [comment]
That is a great question, thank you!

Yes, this is a good way to compare Type values. From godoc for [reflect.Type](https://pkg.go.dev/reflect#Type):

> Type values are comparable, such as with the == operator, so they can be used as map keys. Two Type values are equal if they represent identical types.
