### ISSUE TITLE
Go version is very old

### ISSUE THREAD

**Issue by vault-thirteen** [kr/pretty#89]
The current library uses Go language verion 1.12.

> go 1.12

This version is very old. 
Version 1.12 was released in February 2019 according to the Go's website, https://go.dev/project.
Today is February 2023. Four (4) years have passed !

Thank you.

**Comment by inliquid** [comment]
This line in `go.mod` does not mean "library uses" `go1.12`. This means that it just requires _at least_ `go1.12` (or higher). There are a lot of projects which may use older `gc`, and no point in setting it up to the most recent one, as it will become unusable for many projects.

**Comment by kr** [comment]
Yes, thanks for filing the issue, @vault-thirteen. And @inliquid is correct. You can use any more recent version of Go if you want.
